replicaCount: 1
logLevel: info
watchInterval: "0"
maxPodRestartsPerMinute: 20
component: operator

# Override this to use a custom operator service image.
# If the image name contains a "/", it is assumed to be a full docker image name, including the registry url and tag.
# Otherwise, the helm chart will use {{ .Values.global.registry }}/{{ .Values.image.name }}:{{ .Values.global.tag }}
image:
  name: "operator"

nameOverride: ""
fullnameOverride: ""

deploymentAnnotations: {}

apiService:
  type: ClusterIP
  annotations: {}
webhookService:
  type: ClusterIP
  annotations: {}

runAsNonRoot: true

serviceReconciler:
  enabled: true

ports:
  protocol: TCP
  port: 443
  targetPort: 6500

resources: {}

extraEnvVars: {}

livenessProbe:
  initialDelaySeconds: 3
  periodSeconds: 3
  failureThreshold: 5
readinessProbe:
  initialDelaySeconds: 3
  periodSeconds: 3
  failureThreshold: 5

debug:
  enabled: false
  port: 40000
  initialDelaySeconds: 30000

###################
# Injector Config #
sidecarImagePullPolicy: IfNotPresent
sidecarImageName: "daprd"
sidecarRunAsNonRoot: true
sidecarReadOnlyRootFilesystem: true
sidecarDropALLCapabilities: false
enableK8sDownwardAPIs: false
allowedServiceAccounts: ""
allowedServiceAccountsPrefixNames: ""
preferUsernameAuthOverUID: true
kubeClusterDomain: cluster.local
ignoreEntrypointTolerations: "[{\\\"effect\\\":\\\"NoSchedule\\\",\\\"key\\\":\\\"alibabacloud.com/eci\\\"},{\\\"effect\\\":\\\"NoSchedule\\\",\\\"key\\\":\\\"azure.com/aci\\\"},{\\\"effect\\\":\\\"NoSchedule\\\",\\\"key\\\":\\\"aws\\\"},{\\\"effect\\\":\\\"NoSchedule\\\",\\\"key\\\":\\\"huawei.com/cci\\\"}]"
hostNetwork: false
###################