name: Sync Upstream

env:
  UPSTREAM_URL: "https://github.com/dapr/dapr.git"
  WORKFLOW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  UPSTREAM_BRANCH: "main"
  DOWNSTREAM_BRANCH: "upstream"
  FETCH_ARGS: ""
  MERGE_ARGS: ""
  PUSH_ARGS: ""
  SPAWN_LOGS: "true"

# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 18 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Upstream
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with: 
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ env.WORKFLOW_TOKEN }}
          fetch_args: ${{ env.FETCH_ARGS }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}
          spawn_logs: ${{ env.SPAWN_LOGS }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: dapr upstream sync
          title: Automated - Dapr Upstream Sync
          body: Merging upstream changes into master
          base: master
          branch: upstream
          delete-branch: true
          token: ${{ env.WORKFLOW_TOKEN }}
          labels: upstream-merge,automerge # TODO: Add PR checks and automerge